#! /bin/bash
scp zhch@182.92.83.14:/home/zhch/document/wordnote/database/wordnote.db .

scp zhch@182.92.83.14:/home/zhch/document/wordnote/notes_store.js .

scp -r zhch@182.92.83.14:/home/zhch/document/wordnote/daywords .
